package com.taskmanager.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/***
 * 
 * @author sunny
 *
 */
@Entity
@Table(name="task_table")
public class Task {

	@Id
	@Column(name="task_num") //if we want to make column name and class field name different.
	//@GeneratedValue(strategy=GenerationType.SEQUENCE) // to make task no autogenerated.
	private int taskNum;
	
	@Column(name = "date")
	private String date;
	
	@Column(name = "label")
	private String label;

	@Column(name = "priority")
	private String priority;
	
	public int getTaskNum() {
		return taskNum;
	}

	public void setTaskNum(int taskNum) {
		this.taskNum = taskNum;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}


	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}
}
